export default[
    {
        id:1,
        name:"HMTL",
        color:"#E34F26",
        isDead:false
    },
      {
        id:2,
        name:"CSS",
        color:"#1572B6",
        isDead:false
    },
      {
        id:3,
        name:"Javascript",
        color:"#F7DF1E",
        isDead:false
    },
      {
        id:4,
        name:"React",
        color:"#61DAFB",
        isDead:false
    },
      {
        id:5,
        name:"Typescript",
        color:"#3178C6",
        isDead:false
    },
      {
        id:6,
        name:"Node.js",
        color:"#339933",
        isDead:false
    },
      {
        id:7,
        name:"Python",
        color:"#FFD43B",
        isDead:false
    },
      {
        id:8,
        name:"Ruby",
        color:"#820C02",
        isDead:false
    },
    {
        id:9,
        name:"Assembly",
        color:"#8A9AF1",
        isDead:false
    },


]